set_property IOSTANDARD LVCMOS33 [get_ports {Count[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Count[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports Clock_System]
set_property IOSTANDARD LVCMOS33 [get_ports Reset]
set_property PACKAGE_PIN E3 [get_ports Clock_System]
set_property PACKAGE_PIN J15 [get_ports Reset]
set_property PACKAGE_PIN K15 [get_ports {Count[1]}]
set_property PACKAGE_PIN H17 [get_ports {Count[0]}]
